# Numpy

In [4]:
import numpy as np

> 배열 생성

In [7]:
x = np.array([1.0, 2.0, 3.0])

print(x)

print(type(x))

[1. 2. 3.]
<class 'numpy.ndarray'>


여러가지 타입을 섞는 것도 가능하다.

In [21]:
a = np.array([[5.2,'c'],[4,5]])

print(a)

[['5.2' 'c']
 ['4' '5']]


> Numpy 산술 연산

In [26]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x + y)

print(x - y)

print(x * y)

print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [29]:
x = np.array([1.0, 2.0, 3.0, 6])

print(x + y)

print(x - y)

print(x * y)

print(x / y)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

두 배열의 원소의 수가 다르면 에러가 난다.

**브로드캐스트** : 특정 배열과 한개의 스칼라 값(수치 하나)조합된 연산을 수행해주는 기능

In [30]:
print(x * 5)

[ 5. 10. 15. 30.]


당연하게도 이렇게 섞여 있는 배열에는 안되는 듯 하다.

In [31]:
a = np.array([[5.2,'c'],[4,5]])

a = np.array([[5.2,'c'],[4,5]])

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

> 다차원 배열

In [23]:
a = np.array([[1,2],[3,4]])

print(a)

[[1 2]
 [3 4]]


shape을 사용하면 행렬에 형상을, dtype를 사용하면 데이터 타입을 알 수 있다.

In [24]:
print(a.shape)

print(a.dtype)

(2, 2)
int32
